version: '3.1'
networks:
  code-runner-network:
    driver: bridge

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qiyuhang
      MYSQL_USER: user
      MYSQL_PASSWORD: qiyuhang
      MYSQL_DATABASE: mydb
      TZ: Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - C:\mysql_vol:/var/lib/mysql
    container_name: code-runner-mysql
    networks:
      - code-runner-network
    profiles:
      - database

  # Node.js 服务组
  nodejs-16:
    build:
      context: ./nodejs/16
    networks:
      - code-runner-network
    image: nodejs:16
  nodejs-18:
    build:
      context: ./nodejs/18
    networks:
      - code-runner-network
    image: nodejs:18
  nodejs-20:
    build:
      context: ./nodejs/20
    networks:
      - code-runner-network
    image: nodejs:20
  nodejs-22:
    build:
      context: ./nodejs/22
    networks:
      - code-runner-network
    image: nodejs:22
  # Python 服务组
  python-2:
    build:
      context: ./python/2.7.18
    networks:
      - code-runner-network
    image: python:2
  python-3:
    build:
      context: ./python/3.9.18
    networks:
      - code-runner-network
    image: python:3
  # Java 服务组
  java-8:
    build:
      context: ./java/8
    networks:
      - code-runner-network
    image: java:8
  java-17:
    build:
      context: ./java/17
    networks:
      - code-runner-network
    image: java:17
  java-20:
    build:
      context: ./java/20
    networks:
      - code-runner-network
    image: java:20
  # Go 服务组
  go-1:
    build:
      context: ./go/1.18
    networks:
      - code-runner-network
    image: go:1

  # C++ 服务组
  cpp-11:
    build:
      context: ./cpp/11.5
    networks:
      - code-runner-network
    image: cpp:11
  cpp-14:
    build:
      context: ./cpp/14.2
    networks:
      - code-runner-network
    image: cpp:14
  # PHP 服务组
  php-7:
    build:
      context: ./php/7.4
    networks:
      - code-runner-network
    image: php:7
  php-8:
    build:
      context: ./php/8.4
    networks:
      - code-runner-network
    image: php:8

  # Rust 服务组
  rust-1:
    build:
      context: ./rust/1.83.0
    networks:
      - code-runner-network
    image: rust:1

# mysql数据库服务启动命令
# docker-compose --profile database up -d
